// Setup GUI: a tiny dependency-free local web wizard to write .env.
// Run: npm run setup  -> opens http://localhost:8799 in your browser.
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { exec } from 'node:child_process';

const here = dirname(fileURLToPath(import.meta.url));
const ENV_PATH = join(process.cwd(), '.env');
const PORT = Number(process.env.SETUP_PORT ?? 8799);

// Defaults shown on first run (when no .env exists yet).
const DEFAULTS: Record<string, string> = {
  LLM_PROVIDER: 'ollama',
  OLLAMA_HOST: 'http://127.0.0.1:11434',
  OLLAMA_MODEL: 'qwen2.5:14b',
  LLM_BASE_URL: '',
  LLM_API_KEY: '',
  LLM_MODEL: '',
  SIMBRIEF_USERNAME: '',
  NAVDATA_SOURCES: 'sim,mock',
  NAVDATA_PATH: './navdata/cycle.s3db',
};

function parseEnv(text: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of text.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('=');
    if (eq === -1) continue;
    out[t.slice(0, eq).trim()] = t.slice(eq + 1).trim();
  }
  return out;
}

function readEnv(): Record<string, string> {
  const existing = existsSync(ENV_PATH) ? parseEnv(readFileSync(ENV_PATH, 'utf8')) : {};
  return { ...DEFAULTS, ...existing };
}

function writeEnv(updates: Record<string, string | undefined>): void {
  const merged = { ...readEnv() };
  for (const [k, v] of Object.entries(updates)) {
    if (v !== undefined) merged[k] = v;
  }
  const lines = ['# Generated by `npm run setup`', ''];
  for (const [k, v] of Object.entries(merged)) lines.push(`${k}=${v}`);
  writeFileSync(ENV_PATH, lines.join('\n') + '\n', 'utf8');
}

function send(res: ServerResponse, status: number, contentType: string, body: string | Buffer): void {
  res.writeHead(status, { 'content-type': contentType });
  res.end(body);
}

function sendJson(res: ServerResponse, status: number, obj: unknown): void {
  send(res, status, 'application/json', JSON.stringify(obj));
}

function readBody(req: IncomingMessage): Promise<string> {
  return new Promise((resolve) => {
    let data = '';
    req.on('data', (c) => { data += c; });
    req.on('end', () => resolve(data));
  });
}

async function ollamaModels(host: string): Promise<string[]> {
  const res = await fetch(`${host.replace(/\/+$/, '')}/api/tags`, { signal: AbortSignal.timeout(2500) });
  if (!res.ok) throw new Error(`Ollama ${res.status}`);
  const j = (await res.json()) as { models?: Array<{ name?: string }> };
  return (j.models ?? []).map((m) => m.name ?? '').filter(Boolean);
}

const server = createServer(async (req, res) => {
  const url = new URL(req.url ?? '/', `http://localhost:${PORT}`);
  try {
    if (req.method === 'GET' && url.pathname === '/') {
      send(res, 200, 'text/html; charset=utf-8', readFileSync(join(here, 'index.html')));
    } else if (req.method === 'GET' && url.pathname === '/api/config') {
      sendJson(res, 200, readEnv());
    } else if (req.method === 'GET' && url.pathname === '/api/ollama-models') {
      const host = url.searchParams.get('host') ?? DEFAULTS.OLLAMA_HOST!;
      try {
        sendJson(res, 200, { models: await ollamaModels(host) });
      } catch {
        sendJson(res, 200, { models: [] });
      }
    } else if (req.method === 'POST' && url.pathname === '/api/save') {
      const body = await readBody(req);
      writeEnv(JSON.parse(body) as Record<string, string | undefined>);
      sendJson(res, 200, { ok: true });
    } else {
      send(res, 404, 'text/plain', 'not found');
    }
  } catch (e) {
    sendJson(res, 500, { ok: false, error: (e as Error).message });
  }
});

server.listen(PORT, () => {
  const url = `http://localhost:${PORT}`;
  console.log(`MSFS AI ATC setup -> ${url}  (Ctrl+C to stop)`);
  if (process.platform === 'win32') exec(`cmd /c start "" "${url}"`);
});
